config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  as :user do
    get 'login'  => 'devise/sessions#new', as: :login
    get 'logout' => 'devise/sessions#destroy', as: :logout
    get 'signup' => 'devise/registrations#new', as: :signup
  end

  put 'checkout' => 'checkout#update_cart', as: :checkout_update
  root 'home#index'
  resources :books,       only: [:show]
  resources :addresses,   only: [:create]
  resources :categories,  only: [:show]
  resources :reviews,     only: [:create]
  resources :orders,      only: [:index, :show]
  resources :checkout
  resources :carts,       only: [:index, :update]
  resources :order_items, only: [:create, :destroy]
  resources :users,       only: [:edit, :update, :destroy]

  put 'settings' => 'users#update'
  get 'settings' => 'users#edit'
  get 'categories' => 'books#index', :as => 'categories'
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  include Wicked::Wizard
  before_action :assign_order_to_user
  before_action :authenticate_user!, except: :index
  before_action :check_order, only: :show

  steps :address, :delivery, :payment, :confirm, :complete

  def index
    current_order.subtotal!
    current_order.update_total!
  end

  def show
    @form = StepShowService.new(step, current_order, session).form
    render_wizard
  end

  def update
    @form = StepUpdateService.new(step, current_order, params, session).update
    render_page
  end

  def update_cart
    authorize! :manage, current_order
    update_items
    check_coupon if params[:order]&.[](:coupon).present?
    redirect_back(fallback_location: root_path)
  end

  private

  def render_page
    if need_redirect?
      jump_to(:confirm)
      render_wizard
    else
      @form ? render_wizard(@form) : render_wizard(current_order)
    end
  end

  def need_redirect?
    session[:steps_taken?] &&
      step != :confirm &&
      (@form ? @form.valid? : true)
  end

  def finish_wizard_path
    categories_path
  end

  def assign_order_to_user
    unless current_order.user
      current_order.user = current_user
      current_order.save
    end
  end

  def check_order
    unless %i[complete wicked_finish].include?(step.to_sym)
      redirect_to(checkout_index_path) if current_order.order_items.blank?
    end
  end

  def check_coupon
    coupon = Coupon.where(code: params[:order][:coupon], active: true).first
    if coupon
      coupon.active = false
      current_order.coupon = coupon
    end
    flash[:error] = I18n.t(:coupon_not_found) unless coupon
  end

  def update_items
    params[:order_items].each do |key|
      if order_items_params(key)[:quantity].to_i.positive?
        OrderItem.update(key, order_items_params(key))
      end
    end
  end

  def order_items_params(item)
    params.require(:order_items).require(item).permit(:quantity)
  end
end

app/helpers/checkout_helper.rb
module CheckoutHelper
  def current_step(current_step)
    'active' if current_step == @step
  end

  def checked_delivery?(delivery_id)
    if params[:delivery_id] || current_order.delivery_id
      params[:delivery_id] == delivery_id || current_order.delivery_id == delivery_id
    else
      true
    end
  end
end

app/views/checkout/_address.html.haml
#{obj.full_name}
= @form ? @form.edit_link : nil
%br
#{obj.address}
%br
#{obj.city} #{obj.zip}
%br
#{obj.country.name}
%br
#{t(:phone)} #{obj.phone}

app/views/checkout/_fields.html.haml
- obj = AddressDecorator.decorate(obj)
.form-group{class: add_error_class(obj, :first_name)}
  = f.label :first_name, {class: "control-label font-weight-light", value: t(:first_name)}
  = f.text_field :first_name, {class: "form-control", placeholder: t(:first_name)}
  .span.help-block= show_errors(obj, :first_name)

.form-group{class: add_error_class(obj, :last_name)}
  = f.label :last_name, {class: "control-label font-weight-light", value: t(:last_name)}
  = f.text_field :last_name, {class: "form-control", placeholder: t(:last_name)}
  .span.help-block= show_errors(obj, :last_name)

.form-group{class: add_error_class(obj, :address)}
  = f.label :address, {class: "control-label font-weight-light", value: t(:address)}
  = f.text_field :address, {class: "form-control", placeholder: t(:address)}
  .span.help-block= show_errors(obj, :address)

.form-group{class: add_error_class(obj, :city)}
  = f.label :city, {class: "control-label font-weight-light", value: t(:city)}
  = f.text_field :city, {class: "form-control", placeholder: t(:city)}
  .span.help-block= show_errors(obj, :city)

.form-group{class: add_error_class(obj, :zip)}
  = f.label :zip, {class: "control-label font-weight-light", value: t(:zip)}
  = f.text_field :zip, {class: "form-control", placeholder: t(:zip)}
  .span.help-block= show_errors(obj, :zip)

.form-group{class: add_error_class(obj, :country_id)}
  = f.collection_select(:country_id, Country.all, :id, :name, {include_blank: t(:nothing_selected), selected: obj.show_selected_value, disabled: t(:nothing_selected)}, { id: "country", class: "form-control"})
  .span.help-block= show_errors(obj, :country_id)

.form-group.mb-60{class: add_error_class(obj, :phone)}
  = f.label :phone, {class: "control-label font-weight-light", value: t(:phone)}
  = f.text_field :phone, {class: "form-control", placeholder: t(:example_phone)}
  .span.help-block= show_errors(obj, :phone)

app/views/checkout/_order_products_md.html.haml
- obj ||= current_order
- obj = obj.decorate
%table.table.table-hover
  %tr.no-hover
    %th.col-pic.pl-0
      %span.in-grey-600=t :product
    %th.col-title
    %th.col-price
      %span.in-grey-600=t :price
    %th.col-quantity
      %span.in-grey-600=t :quantity
    %th.col-total
      %span.in-grey-600=t :subtotal
    =obj.delete_button_header
  - obj.decorate.order_items.each do |item|
    %tr
      %td
        .general-img-wrap-table
          %img.cart-img-shadow.pull-left.width-full{src: "#{item.book.pictures.first.image.url}", alt: "#{item.book.title}"}
      %td
        %p.general-title #{item.book.title}
        =item.show_description
      %td
        %span.font-16.in-gold-500 €#{item.book.price}
      %td
        = fields_for 'order_items[]', item do |field|
          =item.quantity_field(field, item)
      %td
        %span.font-16.in-gold-500 €#{item.show_subtotal}
      =item.delete_button(item)

app/views/checkout/_order_products_xs.html.haml
- obj ||= current_order
- obj = obj.decorate
- obj.order_items.each do |item|
  .general-cart-item.divider-lg-bottom
    %button.close.general-cart-close{type: "button", 'aria-label': "Close"}
      %span{'aria-hidden': "true"} &times;
    .general-img-wrap-table
      %img.cart-img-shadow.width-full{src: "#{item.book.pictures.first.image.url}", alt: "#{item.book.title}"}
    %p.general-title #{item.book.title}
    %p.in-grey-600.font-weight-light=item.show_description
    %table.table
      %tr
        %td
          %span.in-grey-600 =t :price
        %td
          %span.font-16.in-gold-500 €#{item.book.price}
      %tr
        %td.vertical-middle
          %span.in-grey-600=t :quantity
        %td
          = fields_for 'order_items[]', item do |field|
            =item.quantity_field(field, item)
      %tr
        %td
          %span.in-grey-600=t :subtotal
        %td
          %span.font-16.in-gold-500 €#{item.show_subtotal}

app/views/checkout/_quantity_field.html.haml
.input-group
  %div.input-link.dec.button{id: "dec-#{item.id}", onclick: "inc_dec('-', this)"}
    %i.fa.fa-minus.line-height-40
  = field.text_field :quantity, class: "form-control quantity-input", min: 1, value: "#{item.quantity}", 'data-quantity-item-id' => item.id
  %div.input-link.inc.button{id: "inc-#{item.id}", onclick: "inc_dec('+', this)"}
    %i.fa.fa-plus.line-height-40

app/views/checkout/_steps.html.haml
%h1.general-title-margin=t :checkout
%ul.steps.list-inline
  %li.step{class: current_step(:address)}
    %span.step-number 1
    %span.step-text.hidden-xs=t :address
  %li.step-divider
  %li.step{class: current_step(:delivery)}
    %span.step-number 2
    %span.step-text.hidden-xs=t :delivery
  %li.step-divider
  %li.step{class: current_step(:payment)}
    %span.step-number 3
    %span.step-text.hidden-xs=t :payment
  %li.step-divider
  %li.step{class: current_step(:confirm)}
    %span.step-number 4
    %span.step-text.hidden-xs=t :confirm
  %li.step-divider
  %li.step{class: current_step(:complete)}
    %span.step-number 5
    %span.step-text.hidden-xs=t :complete

app/views/checkout/_summary.html.haml
- order ||= current_order
- order = order.decorate
%tr
  %td
    %p.font-16=t :item_total
  %td
    %p.font-16 €#{order.subtotal}
= order.summary_coupon
= order.summary_delivery
%tr
  %td
    %p.font-16=t :order_total
  %td
    %p.font-16 €#{ order.show_total }

app/views/checkout/address.html.haml
%main.container
  = render partial: '/checkout/steps'
  = form_for @form, url: wizard_path, method: :put do |f|
    .hidden-xs.hidden-sm
      .row
        .col-md-5
          %h3.general-subtitle=t :billing_address
          %p.general-info-text=t :fields_required
        .col-md-5.col-md-offset-1
          %h3.general-subtitle=t :shipping_address
    .row
      .col-md-5.mb-40
        .visible-xs.visible-sm
          %h3.general-subtitle=t :billing_address
          %p.general-info-text=t :fields_required
        = f.fields_for @form.billing_address do |b|
          = render partial: '/checkout/fields', locals: {f: b, obj: @form.billing_address}
      .col-md-5.col-md-offset-1.mb-60
        .visible-xs.visible-sm
          %h3.general-subtitle=t :shipping_address
        #shipping_address_form
          = f.fields_for @form.shipping_address do |s|
            = render partial: '/checkout/fields', locals: {f: s, obj: @form.shipping_address}
        .form-group.checkbox
          %label.font-weight-light.pl-0
            = f.fields_for @form.shipping_address do |s|
              = s.check_box :use_billing_address, onclick: 'hide_block(this)', hidden: true, class: 'checkbox-input'
              %span.checkbox-icon
                %i.fa.fa-check
              %span.checkbox-text=t :use_billing_address
    .general-text-align.mb-60
      %p.in-gold-500.font-18=t :order_summary
      %table.general-summary-table
        = render partial: '/checkout/summary'
        = f.submit t(:save_and_continue), class: "btn btn-primary center-block mb-20"
= javascript_include_tag "checkout.js"

app/views/checkout/complete.html.haml
%main.container.general-main-wrap
  = render partial: '/checkout/steps'
  .text-center.mb-40
    %h3.general-subtitle=t :thank_for_order
    %p.font-weight-light=t :confirmation_sent, email: current_user.email
  .row.mb-20
    .col-sm-6
      .visible-xs
        %p.general-order-number.mb-0 #{t(:order)} # #{@form.number}
        %p.general-address.mb-30 #{@form.updated_at.strftime('%B %-d %C')}
      %p.general-address
        = render partial: '/checkout/address', locals: { obj: @form.billing_address }
    .col-sm-6.hidden-xs.text-right
      %p.general-order-number.mb-0 #{t(:order)} # #{@form.number}
      %p.general-address.mb-30 #{@form.updated_at.strftime('%B %-d %Y')}
  .visible-xs
    = render partial: '/checkout/order_products_xs', locals: { obj: @form }
  .hidden-xs.divider-lg.pt-20
    = render partial: '/checkout/order_products_md', locals: { obj: @form }
  .text-center.general-text-right
    %p.in-gold-500.font-18=t :order_summary
    %table.general-summary-table.general-summary-table-right.general-text-right
      = render partial: '/checkout/summary', locals: {order: @form}
  .text-center
    = button_to t(:back_to_store), wizard_path(:complete), {method: :put, class: "btn btn-default mb-20"}

app/views/checkout/confirm.html.haml
%main.container.general-main-wrap
  = render partial: '/checkout/steps'
  .row.mb-20
    .col-sm-3
      %h3.general-subtitle=t :shipping_address
      %p.general-address
        = @form.show_shipping_address
    .col-sm-3
      %h3.general-subtitle=t :billing_address
      %p.general-address
        = @form.show_billing_address
    .col-sm-3
      %h3.general-subtitle=t :shipments
      %p.general-address
        #{current_order.delivery.name}
        = link_to t(:edit), wizard_path(:delivery), class: 'general-edit'
    .col-sm-3
      %h3.general-subtitle Payment Information
      %p.general-address
        #{current_order.decorate.filtred_card_number}
        = link_to 'edit', wizard_path(:payment), class: 'general-edit'
        %br
        #{current_order.credit_card.date}
  .visible-xs
    = render partial: '/checkout/order_products_xs'
  .hidden-xs.divider-lg.pt-20
    = render partial: '/checkout/order_products_md'
  .text-center.general-text-right
    %p.in-gold-500.font-18=t :order_summary
    %table.general-summary-table.general-summary-table-right.general-text-right
      = render partial: '/checkout/summary'
  .text-center
    = button_to t(:place_order), wizard_path, {method: :put, class: "btn btn-default mb-20"}

app/views/checkout/delivery.html.haml
%main.container.general-main-wrap
  = render partial: '/checkout/steps'
  %h3.general-subtitle=t :delivery
  .visible-xs
    = form_for current_order, url: wizard_path, method: :put do |f|
      -@form.each do |delivery|
        .general-cart-item.divider-lg-bottom
          %table.table
            %tr
              %td.col-half
                %span.in-grey-600=t :method
              %td.col-half
                .form-group.radio.mt-0.mb-0
                  %label.font-16.font-weight-light.pl-0
                    =f.radio_button :delivery_id, delivery.id, class: "radio-input", hidden: "true"
                    %span.radio-icon
                    %span.radio-text #{delivery.name}
            %tr
              %td
                %span.in-grey-600=t :days
              %td
                %span.font-16.font-weight-light #{delivery.interval}
            %tr
              %td
                %span.in-grey-600=t :price
              %td
        %span.font-16.in-gold-500 €#{delivery.price}
      .general-text-align
        %p.in-gold-500.font-18=t :order_summary
        %table.general-summary-table
          = render partial: '/checkout/summary'
      .text-center
        = f.submit t(:save_and_continue), class: "btn btn-primary center-block mb-20"
  .hidden-xs.mb-res-50
    = form_for current_order, url: wizard_path, method: :put do |f|
      %table.table.table-hover
        %thead
          %tr
            %th.col-method
              %span.in-grey-600.ml-40=t :method
            %th
              %span.in-grey-600=t :days
            %th
              %span.in-grey-600=t :price
        %tbody
          -@form.each do |delivery|
            %tr
              %td
                .form-group.radio.mt-0.mb-0
                  %label.font-16.font-weight-light.pl-0
                    =f.radio_button :delivery, delivery.id, checked: checked_delivery?(delivery.id), class: "radio-input", hidden: "true"
                    %span.radio-icon
                    %span.radio-text #{delivery.name}
              %td
                %span #{delivery.interval}
              %td
                %span.font-16.in-gold-500 €#{delivery.price}
      .general-text-align
        %p.in-gold-500.font-18=t :order_summary
        %table.general-summary-table
          = render partial: '/checkout/summary'
      .text-center
        = f.submit t(:save_and_continue), class: "btn btn-primary center-block mb-20"

app/views/checkout/index.html.haml
%main.container.general-main-wrap
  - if current_order.order_items.any?
    %h1.general-title-margin=t :cart
    %p.notice=flash[:error]
    .visible-xs
      = form_for current_order, url: checkout_update_path, method: :put do |f|
        = render partial: '/checkout/order_products_xs'
        = f.submit t(:update_cart), class: "btn btn-primary mb-15 res-block"
        .col-sm-8
          .res-mr-200.text-center.general-text-right
            %p.in-gold-500.font-18=t(:order_summary)
            %table.general-summary-table.general-summary-table-right.general-text-right
              = render partial: '/checkout/summary'
    .hidden-xs
      = form_for current_order, url: checkout_update_path, method: :put do |f|
        = render partial: '/checkout/order_products_md'
        .general-order-wrap
          .row
            .col-sm-4
              .input-group.general-input-group
                %label.font-weight-light=t :enter_coupon
                = f.text_field :coupon, { class: "form-control mb-30", placeholder: t(:enter_coupon), value: current_order.coupon ? current_order.coupon.code : '', disabled: current_order.coupon ? true : false }
                %div
                  = f.submit t(:update_cart), class: "btn btn-primary mb-15 res-block"
            .col-sm-8
              .res-mr-200.text-center.general-text-right
                %p.in-gold-500.font-18=t :order_summary
                %table.general-summary-table.general-summary-table-right.general-text-right
                  = render partial: '/checkout/summary'
    = button_to t(:checkout),  wizard_path(:address), method: :get, class: "btn btn-default mb-20 visible-xs-inline-block"
    = button_to t(:checkout),  wizard_path(:address), method: :get, class: "btn btn-default mb-20 hidden-xs center-block"
  - else
    %h1.general-title-margin=t :cart_empty
= javascript_include_tag "checkout.js"

app/views/checkout/payment.html.haml
%main.container.mb-res-50
  = render partial: '/checkout/steps'
  %h3.general-subtitle Credit Card
  = form_for @form, url: wizard_path, class: "max-600 mb-80", method: :put do |f|
    .form-group{class: add_error_class(@form, :number)}
      = f.label :number, {class: "control-label font-weight-light", value: t(:card_number)}
      = f.text_field :number, {class: "form-control", placeholder: t(:card_number)}
      .span.help-block= show_errors(@form, :number)
    .row
      .col-sm-6
        .form-group{class: add_error_class(@form, :name)}
          = f.label :name, {class: "control-label font-weight-light", value: t(:name_on_card)}
          = f.text_field :name, {class: "form-control", placeholder: t(:name_on_card)}
          .span.help-block= show_errors(@form, :name)
      .col-sm-3
        .form-group{class: add_error_class(@form, :date)}
          = f.label :date, {class: "control-label font-weight-light", value: t(:date_format)}
          = f.text_field :date, {class: "form-control", placeholder: t(:date_format)}
          .span.help-block= show_errors(@form, :date)
      .col-sm-3
        .form-group{class: "relative #{add_error_class(@form, :cvv)}"}
          = f.label :cvv, {class: "control-label font-weight-light", value: t(:cvv)}
          = f.text_field :cvv, {class: "form-control", placeholder: t(:cvv)}
          %i.fa.fa-question-circle.general-form-help.font-18{title: t(:cvv_help)}
          .span.help-block= show_errors(@form, :cvv)
    .general-text-align
      %p.in-gold-500.font-18=t :order_summary
      %table.general-summary-table
        = render partial: '/checkout/summary'
    .text-center
      = f.submit t(:save_and_continue), class: "btn btn-primary center-block mb-20"