config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  as :user do
    get 'login'  => 'devise/sessions#new', as: :login
    get 'logout' => 'devise/sessions#destroy', as: :logout
    get 'signup' => 'devise/registrations#new', as: :signup
  end

  put 'checkout' => 'checkout#update_cart', as: :checkout_update
  root 'home#index'
  resources :books,       only: [:show]
  resources :addresses,   only: [:create]
  resources :categories,  only: [:show]
  resources :reviews,     only: [:create]
  resources :orders,      only: [:index, :show]
  resources :checkout
  resources :carts,       only: [:index, :update]
  resources :order_items, only: [:create, :destroy]
  resources :users,       only: [:edit, :update, :destroy]

  put 'settings' => 'users#update'
  get 'settings' => 'users#edit'
  get 'categories' => 'books#index', :as => 'categories'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    alias_action :read, :update, :destroy, to: :all_excluding_create

    user ||= User.new
    can :manage, :all if user.is_admin?

    can :manage, User, id: user.id
    can :manage, Order, user_id: user.id
    can :create, OrderItem
    can :all_excluding_create, OrderItem do |order_item|
      order_item.order.user_id == user.id
    end
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :addressable, polymorphic: true
  belongs_to :country

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/author.rb
class Author < ApplicationRecord
  validates :first_name, :last_name, presence: true

  has_and_belongs_to_many :books

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/billing_address.rb
class BillingAddress < Address
end

app/models/book.rb
class Book < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  validates :title, :price, :description, :category_id, presence: true
  default_scope -> { preload(:authors, :pictures) }

  has_and_belongs_to_many :authors
  has_and_belongs_to_many :materials
  has_many :order_items
  has_many :pictures, dependent: :destroy
  has_many :reviews, -> { where(aasm_state: 'approved').order(updated_at: :desc) }
  belongs_to :category
  accepts_nested_attributes_for :pictures, allow_destroy: true

  def create_associated_image(image)
    pictures.create(image: image)
  end

  def self.bestsellers(items)
    with_models = BooksQuery.new.with_associate_models
    items_quantity = BooksQuery.new(with_models).sum_items_quantity
    items_quantity.order('quantity desc').first(items)
  end

  def self.latest_books(items)
    includes(:pictures, :authors).order(created_at: :desc).limit(items)
  end

  def self.with_category_filter(category)
    category = category&.humanize || 'Mobile development'
    joins(:category).where("categories.name = '#{category}'")
  end

  def self.with_filter(filter)
    BooksQuery.new.with_filter(filter)
  end
end

app/models/category.rb
class Category < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :books

  validates :name, presence: true
end

app/models/country.rb
class Country < ApplicationRecord
  default_scope { order(name: :asc) }
end

app/models/coupon.rb
class Coupon < ApplicationRecord
  belongs_to :order
  validates :code, :value, presence: true
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  belongs_to :order
end

app/models/delivery.rb
class Delivery < ApplicationRecord
  validates :name, :interval, :price, presence: true
end

app/models/material.rb
class Material < ApplicationRecord
  has_and_belongs_to_many :books
end

app/models/order.rb
class Order < ApplicationRecord
  include AASM

  after_create :generate_order_number

  has_one :coupon
  has_one :credit_card
  has_one :shipping_address, as: :addressable, dependent: :destroy
  has_one :billing_address, as: :addressable, dependent: :destroy
  has_many :order_items
  belongs_to :user
  belongs_to :delivery

  aasm do
    state :pending, initial: true
    state :waiting_for_processing
    state :in_progress
    state :in_delivery
    state :delivered
    state :cancelled

    event :waiting_processing do
      transitions from: :pending, to: :waiting_for_processing
    end

    event :progress do
      transitions from: :waiting_for_processing, to: :in_progress
    end

    event :delivered do
      transitions from: :in_progress, to: :in_delivery
    end

    event :complete do
      transitions from: :in_delivery, to: :delivered
    end

    event :cancelled do
      transitions from: Order.aasm.states.map(&:name) - [:cancelled], to: :cancelled
    end
  end

  def self.with_filter(filter)
    if Order.aasm.states.map(&:name).include?(filter&.to_sym)
      where(aasm_state: filter)
    else
      all
    end
  end

  def update_total!
    estimation = coupon ? coupon.value : 0
    estimation -= delivery.price if delivery
    self.total = subtotal - estimation
    save
  end

  def subtotal!
    self.subtotal = order_items.collect { |item| item.quantity * item.book.price }.sum
    save
  end

  private

  def generate_order_number
    update!(number: format('R%08d', id))
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :book

  default_scope -> { preload(:book) }
end

app/models/picture.rb
class Picture < ApplicationRecord
  validates :image, :book_id, presence: true

  belongs_to :book

  mount_uploader :image, BookCoverUploader
end

app/models/review.rb
class Review < ApplicationRecord
  include AASM

  belongs_to :book
  belongs_to :user

  TEXT_FORMAT = %r[[a-z]|[0-9]|[!#$%&'*+-\/=?^_`{|}~]]i
  validates :title, :message, :score, :user_id, :book_id, presence: true
  validates :title, length: { maximum: 80 }
  validates :title, :message, format: { with: TEXT_FORMAT }
  validates :message, length: { maximum: 500 }
  validates :score, numericality: { greater_than: 0, less_than: 6 }

  aasm do
    state :unprocessed, initial: true
    state :approved
    state :rejected

    event :approve do
      transitions from: %i[unprocessed rejected], to: :approved
    end

    event :reject do
      transitions from: %i[unprocessed approved], to: :rejected
    end
  end
end

app/models/shipping_address.rb
class ShippingAddress < Address
end

app/models/user.rb
class User < ApplicationRecord
  has_one :shipping_address, as: :addressable, dependent: :destroy
  has_one :billing_address, as: :addressable, dependent: :destroy
  has_many :reviews
  has_many :orders
  has_many :order_items, through: :orders

  devise :database_authenticatable, :recoverable,
         :rememberable, :trackable, :validatable,
         :omniauthable, :registerable

  mount_uploader :avatar, AvatarUploader

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }
  validates :password, format: { with: /(?=^.{8,}$)(?=.*[\d])(?=.*[a-z])(?=.*[A-Z])/ }

  def self.new_with_session(params, session)
    super.tap do |user|
      data = session['devise.facebook_data']['extra']['raw_info'] if session['devise.facebook_data']
      user.email = data['email'] if user.email.blank? && data
    end
  end

  def update_email(value)
    self.email = value
    valid?
    if errors[:email].blank?
      update_column(:email, value)
      true
    else
      errors.delete(:password)
      false
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @latest_books = Book.with_category_filter(params['category']).latest_books(3)
    @bestsellers = Book.with_category_filter(params['category']).bestsellers(4)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def filter_state
    params[:filter]&.humanize
  end
end

app/helpers/checkout_helper.rb
module CheckoutHelper
  def current_step(current_step)
    'active' if current_step == @step
  end

  def checked_delivery?(delivery_id)
    if params[:delivery_id] || current_order.delivery_id
      params[:delivery_id] == delivery_id || current_order.delivery_id == delivery_id
    else
      true
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def active_tab
    '#privacy' unless (params.keys & %w[email_form password_form]).empty?
  end
end

app/views/home/index.html.haml
%main.container
  #slider.carousel.slide{'data-ride': "carousel"}
    %ol.carousel-indicators.general-carousel-indicators
      %li.active{'data-target': "#slider", 'data-slide-to': "0"}
      %li{'data-target': "#slider", 'data-slide-to': "1"}
    .carousel-inner{role: "listbox"}
      - flag = true
      - @latest_books.each do |book|
        .item{ class: (flag ? 'active' : '') }
          .row
            .col-sm-5
              .general-img-wrap
                =link_to book do
                  %img.img-shadow.general-thumbnail-img.width-full{src: book.pictures.first.image.url, alt: "#{book.title}"}
            .col-sm-7
              .mb-60
                %h1= book.title
                %p.lead= markdown(book.description)
                %p.in-grey-600.small= separated book.authors, :full_name
                .general-align.pt-20
                  =button_to t(:buy_now), order_items_path(book_id: book.id), remote: true, class: "btn btn-primary", method: :post
                  - flag = false
    %a.left.carousel-control{href: "#slider", role: "button", 'data-slide': "prev"}
      %span.icon-prev{'aria-hidden': "true"}
      %span.sr-only=t :previous
    %a.right.carousel-control{href: "#slider", role: "button", 'data-slide': "next"}
      %span.icon-next{'aria-hidden': "true"}
      %span.sr-only=t :next
.container
  .jumbotron.text-center.mb-0
    %h2.h1=t :welcome
    .mb-res-50
      %p.in-grey-600=t :description
    =button_to t(:get_started), categories_path, class: "btn btn-default", method: :get
  .mb-35
    %h3=t :best_sellers
    .row
    - @bestsellers.each do |bestseller|
      .col-sm-6.col-md-3
        .general-thumb-wrap
          .thumbnail.general-thumbnail
            =image_tag bestseller.pictures.first.image.url(:thumb), alt: bestseller.title, class: 'img-shadow general-thumbnail-img'
            .thumb-hover
              .general-thumb-link-wrap
                =link_to bestseller, class: 'thumb-hover-link' do
                  %i.fa.fa-eye.thumb-icon{'aria-hidden': "true"}
                =link_to order_items_path(book_id: bestseller.id), remote: true, class: "thumb-hover-link", method: :post do
                  %i.fa.fa-shopping-cart.thumb-icon
        .mb-35
          .clearfix
            %p.pull-right.font-16.in-gold-500= "€#{bestseller.price}"
            =link_to bestseller do
              %p.general-title.mr-55= bestseller.title
          %span.divider-sm
          %p.in-grey-600.small= separated bestseller.authors, :full_name