config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  as :user do
    get 'login'  => 'devise/sessions#new', as: :login
    get 'logout' => 'devise/sessions#destroy', as: :logout
    get 'signup' => 'devise/registrations#new', as: :signup
  end

  put 'checkout' => 'checkout#update_cart', as: :checkout_update
  root 'home#index'
  resources :books,       only: [:show]
  resources :addresses,   only: [:create]
  resources :categories,  only: [:show]
  resources :reviews,     only: [:create]
  resources :orders,      only: [:index, :show]
  resources :checkout
  resources :carts,       only: [:index, :update]
  resources :order_items, only: [:create, :destroy]
  resources :users,       only: [:edit, :update, :destroy]

  put 'settings' => 'users#update'
  get 'settings' => 'users#edit'
  get 'categories' => 'books#index', :as => 'categories'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    alias_action :read, :update, :destroy, to: :all_excluding_create

    user ||= User.new
    can :manage, :all if user.is_admin?

    can :manage, User, id: user.id
    can :manage, Order, user_id: user.id
    can :create, OrderItem
    can :all_excluding_create, OrderItem do |order_item|
      order_item.order.user_id == user.id
    end
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :addressable, polymorphic: true
  belongs_to :country

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/author.rb
class Author < ApplicationRecord
  validates :first_name, :last_name, presence: true

  has_and_belongs_to_many :books

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/billing_address.rb
class BillingAddress < Address
end

app/models/book.rb
class Book < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  validates :title, :price, :description, :category_id, presence: true
  default_scope -> { preload(:authors, :pictures) }

  has_and_belongs_to_many :authors
  has_and_belongs_to_many :materials
  has_many :order_items
  has_many :pictures, dependent: :destroy
  has_many :reviews, -> { where(aasm_state: 'approved').order(updated_at: :desc) }
  belongs_to :category
  accepts_nested_attributes_for :pictures, allow_destroy: true

  def create_associated_image(image)
    pictures.create(image: image)
  end

  def self.bestsellers(items)
    with_models = BooksQuery.new.with_associate_models
    items_quantity = BooksQuery.new(with_models).sum_items_quantity
    items_quantity.order('quantity desc').first(items)
  end

  def self.latest_books(items)
    includes(:pictures, :authors).order(created_at: :desc).limit(items)
  end

  def self.with_category_filter(category)
    category = category&.humanize || 'Mobile development'
    joins(:category).where("categories.name = '#{category}'")
  end

  def self.with_filter(filter)
    BooksQuery.new.with_filter(filter)
  end
end

app/models/category.rb
class Category < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :books

  validates :name, presence: true
end

app/models/country.rb
class Country < ApplicationRecord
  default_scope { order(name: :asc) }
end

app/models/coupon.rb
class Coupon < ApplicationRecord
  belongs_to :order
  validates :code, :value, presence: true
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  belongs_to :order
end

app/models/delivery.rb
class Delivery < ApplicationRecord
  validates :name, :interval, :price, presence: true
end

app/models/material.rb
class Material < ApplicationRecord
  has_and_belongs_to_many :books
end

app/models/order.rb
class Order < ApplicationRecord
  include AASM

  after_create :generate_order_number

  has_one :coupon
  has_one :credit_card
  has_one :shipping_address, as: :addressable, dependent: :destroy
  has_one :billing_address, as: :addressable, dependent: :destroy
  has_many :order_items
  belongs_to :user
  belongs_to :delivery

  aasm do
    state :pending, initial: true
    state :waiting_for_processing
    state :in_progress
    state :in_delivery
    state :delivered
    state :cancelled

    event :waiting_processing do
      transitions from: :pending, to: :waiting_for_processing
    end

    event :progress do
      transitions from: :waiting_for_processing, to: :in_progress
    end

    event :delivered do
      transitions from: :in_progress, to: :in_delivery
    end

    event :complete do
      transitions from: :in_delivery, to: :delivered
    end

    event :cancelled do
      transitions from: Order.aasm.states.map(&:name) - [:cancelled], to: :cancelled
    end
  end

  def self.with_filter(filter)
    if Order.aasm.states.map(&:name).include?(filter&.to_sym)
      where(aasm_state: filter)
    else
      all
    end
  end

  def update_total!
    estimation = coupon ? coupon.value : 0
    estimation -= delivery.price if delivery
    self.total = subtotal - estimation
    save
  end

  def subtotal!
    self.subtotal = order_items.collect { |item| item.quantity * item.book.price }.sum
    save
  end

  private

  def generate_order_number
    update!(number: format('R%08d', id))
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :book

  default_scope -> { preload(:book) }
end

app/models/picture.rb
class Picture < ApplicationRecord
  validates :image, :book_id, presence: true

  belongs_to :book

  mount_uploader :image, BookCoverUploader
end

app/models/review.rb
class Review < ApplicationRecord
  include AASM

  belongs_to :book
  belongs_to :user

  TEXT_FORMAT = %r[[a-z]|[0-9]|[!#$%&'*+-\/=?^_`{|}~]]i
  validates :title, :message, :score, :user_id, :book_id, presence: true
  validates :title, length: { maximum: 80 }
  validates :title, :message, format: { with: TEXT_FORMAT }
  validates :message, length: { maximum: 500 }
  validates :score, numericality: { greater_than: 0, less_than: 6 }

  aasm do
    state :unprocessed, initial: true
    state :approved
    state :rejected

    event :approve do
      transitions from: %i[unprocessed rejected], to: :approved
    end

    event :reject do
      transitions from: %i[unprocessed approved], to: :rejected
    end
  end
end

app/models/shipping_address.rb
class ShippingAddress < Address
end

app/models/user.rb
class User < ApplicationRecord
  has_one :shipping_address, as: :addressable, dependent: :destroy
  has_one :billing_address, as: :addressable, dependent: :destroy
  has_many :reviews
  has_many :orders
  has_many :order_items, through: :orders

  devise :database_authenticatable, :recoverable,
         :rememberable, :trackable, :validatable,
         :omniauthable, :registerable

  mount_uploader :avatar, AvatarUploader

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }
  validates :password, format: { with: /(?=^.{8,}$)(?=.*[\d])(?=.*[a-z])(?=.*[A-Z])/ }

  def self.new_with_session(params, session)
    super.tap do |user|
      data = session['devise.facebook_data']['extra']['raw_info'] if session['devise.facebook_data']
      user.email = data['email'] if user.email.blank? && data
    end
  end

  def update_email(value)
    self.email = value
    valid?
    if errors[:email].blank?
      update_column(:email, value)
      true
    else
      errors.delete(:password)
      false
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def filter_state
    params[:filter]&.humanize
  end
end

app/helpers/checkout_helper.rb
module CheckoutHelper
  def current_step(current_step)
    'active' if current_step == @step
  end

  def checked_delivery?(delivery_id)
    if params[:delivery_id] || current_order.delivery_id
      params[:delivery_id] == delivery_id || current_order.delivery_id == delivery_id
    else
      true
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def active_tab
    '#privacy' unless (params.keys & %w[email_form password_form]).empty?
  end
end

app/views/carts/_order_products_md.html.haml
- obj ||= current_order
- obj = obj.decorate
%table.table.table-hover
  %tr.no-hover
    %th.col-pic.pl-0
      %span.in-grey-600=t :product
    %th.col-title
    %th.col-price
      %span.in-grey-600=t :price
    %th.col-quantity
      %span.in-grey-600=t :quantity
    %th.col-total
      %span.in-grey-600=t :subtotal
    =obj.delete_button_header
  - obj.decorate.order_items.each do |item|
    %tr
      %td
        .general-img-wrap-table
          %img.cart-img-shadow.pull-left.width-full{src: "#{item.book.pictures.first.image.url}", alt: "#{item.book.title}"}
      %td
        %p.general-title #{item.book.title}
        =item.show_description
      %td
        %span.font-16.in-gold-500 €#{item.book.price}
      %td
        = fields_for 'order_items[]', item do |field|
          =item.quantity_field(field, item)
      %td
        %span.font-16.in-gold-500 €#{item.quantity * item.book.price}
      =item.delete_button(item)

app/views/carts/_order_products_xs.html.haml
- obj ||= current_order
- obj = obj.decorate
- obj.order_items.each do |item|
  .general-cart-item.divider-lg-bottom
    %button.close.general-cart-close{type: "button", 'aria-label': "Close"}
      %span{'aria-hidden': "true"} &times;
    .general-img-wrap-table
      %img.cart-img-shadow.width-full{src: "#{item.book.pictures.first.image.url}", alt: "#{item.book.title}"}
    %p.general-title #{item.book.title}
    %p.in-grey-600.font-weight-light=item.show_description
    %table.table
      %tr
        %td
          %span.in-grey-600 =t :price
        %td
          %span.font-16.in-gold-500 €#{item.book.price}
      %tr
        %td.vertical-middle
          %span.in-grey-600=t :quantity
        %td
          = fields_for 'order_items[]', item do |field|
            =item.quantity_field(field, item)
      %tr
        %td
          %span.in-grey-600=t :subtotal
        %td
          %span.font-16.in-gold-500 €#{item.quantity * item.book.price}

app/views/carts/_quantity_field.html.haml
.input-group
  %div.input-link.dec.button{id: "dec-#{item.id}", onclick: "inc_dec('-', this)"}
    %i.fa.fa-minus.line-height-40
  = field.text_field :quantity, class: "order-items-#{item.id}-quantity form-control quantity-input", min: 1, value: "#{item.quantity}"
  %div.input-link.inc.button{id: "inc-#{item.id}", onclick: "inc_dec('+', this)"}
    %i.fa.fa-plus.line-height-40

app/views/carts/index.html.haml
%main.container.general-main-wrap
  - if current_order.order_items.any?
    %h1.general-title-margin=t :cart
    .visible-xs
      = form_for current_order, url: cart_path(current_order), method: :put do |f|
        = render partial: '/carts/order_products_xs'
        = f.submit t(:update_cart), class: "btn btn-primary mb-15 res-block"
        .col-sm-8
          .res-mr-200.text-center.general-text-right
            %p.in-gold-500.font-18=t(:order_summary)
            %table.general-summary-table.general-summary-table-right.general-text-right
              = render partial: '/checkout/summary'
    .hidden-xs
      = form_for current_order, url: cart_path(current_order), method: :put do |f|
        = render partial: '/carts/order_products_md'
        .general-order-wrap
          .row
            .col-sm-4
              .input-group.general-input-group
                %label.font-weight-light=t :enter_coupon
                = f.text_field :coupon, { class: "form-control mb-30", placeholder: t(:enter_coupon), value: current_order.coupon ? current_order.coupon.code : '', disabled: current_order.coupon ? true : false }
                %div
                  = f.submit t(:update_cart), class: "btn btn-primary mb-15 res-block"
            .col-sm-8
              .res-mr-200.text-center.general-text-right
                %p.in-gold-500.font-18=t :order_summary
                %table.general-summary-table.general-summary-table-right.general-text-right
                  = render partial: '/checkout/summary'
    = button_to t(:checkout),  checkout_index_path, method: :get, class: "btn btn-default mb-20 visible-xs-inline-block"
    = button_to t(:checkout),  checkout_index_path, method: :get, class: "btn btn-default mb-20 hidden-xs center-block"
  - else
    %h1.general-title-margin=t :cart_empty
:javascript

  function inc_dec(sign, el){
    let id = Number(el.id.match(/\d+/));
    let value = $('#order_items_'+id+'_quantity').val() * 1;

    if (sign == '+'){
      value += 1;
    }else{
      if(value >= 2){
        value -= 1;
      }
    }
    $('.order-items-'+id+'-quantity').each(function() {
      $(this).val(value);
    });
  }

app/views/layouts/_footer.html.haml
%footer.navbar-inverse
  .container
    .row
      .col-sm-9
        %ul.list-inline.general-align.mb-25
          %li
            =link_to t(:home), '/', class: 'nav-link'
          %li
            =link_to t(:shop), '/categories', class: 'nav-link'
          - if user_signed_in?
            %li
              =link_to t(:orders), '/orders', class: 'nav-link'
            %li
              =link_to t(:settings), '/settings', class: 'nav-link'
      .col-sm-3
        %p.general-nav-mail support@bookstore.com
        %p.general-nav-number (555)-555-5555
        %ul.list-inline.general-align
          %li
            =link_to '#', class: 'nav-link' do
              %i.fa.fa-facebook{'aria-hidden': "true"}
          %li
            =link_to '#', class: 'nav-link' do
              %i.fa.fa-twitter{'aria-hidden': "true"}
          %li
            =link_to '#', class: 'nav-link' do
              %i.fa.fa-google-plus{'aria-hidden': "true"}
          %li
            =link_to '#', class: 'nav-link' do
              %i.fa.fa-instagram{'aria-hidden': "true"}

app/views/layouts/_header.html.haml
%header.navbar.navbar-default
  .container
    .navbar-header
      %button.navbar-toggle.pull-left.ml-15{type: "button", 'data-toggle': "collapse", 'data-target': "#navbar"}
        %span.sr-only
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      =link_to t(:shop_name), root_path, class: 'navbar-brand'
      =link_to checkout_index_path, class: 'shop-link pull-right visible-xs' do
        %span.shop-icon
          %span.shop-quantity #{items_in_cart}
    =link_to checkout_index_path, class: 'shop-link pull-right hidden-xs' do
      %span.shop-icon
        %span.shop-quantity #{items_in_cart}
    #navbar.navbar-collapse.collapse.pl-30{'aria-expanded': "false"}
      .visible-xs
        %button.close{type: "button", 'aria-label': "Close"}
          %span{'aria-hidden': "true"} &times;
        %ul.nav.navbar-nav
          %li
            %a{type: "button", 'data-toggle': "collapse", href: "/", 'aria-expanded': "false", 'aria-controls': "menu"}=t :home
            %ul#menu.collapse.list-unstyled.pl-30.mb-10{'aria-expanded': "false"}
              = render partial: '/layouts/navbar_categories_options'
          %li
            %a{type: "button", 'data-toggle': "collapse", href: "/categories", 'aria-expanded': "false", 'aria-controls': "menu"}=t :shop
            %ul#menu.collapse.list-unstyled.pl-30.mb-10{'aria-expanded': "false"}
            - categories.each do |category|
              %li
                =link_to category.name, category, class: 'collapse-link'
            - if user_signed_in?
              %li
                =link_to t(:settings), settings_path
        - if user_signed_in?
          %li
            %a{type: "button", 'data-toggle': "dropdown", href: "/", 'aria-expanded': "false"}=t :my_account
            %ul.dropdown-menu
              %li
                =link_to t(:orders), orders_path, class: 'collapse-link'
              %li
                =link_to t(:settings), settings_path, class: 'collapse-link'
              %li.divider{role: "separator"}
              %li
                =link_to t(:log_out), logout_path, class: 'collapse-link'
        - else
          %li
            =link_to t(:log_in), login_path
          %li
            =link_to t(:sign_up), signup_path
      .hidden-xs
        %ul.nav.navbar-nav
          %li
            %a.dropdown-toggle{href: "/", 'data-toggle': "dropdown", role: "button", 'aria-haspopup': "true", 'aria-expanded': "false"}=t :home
            %ul.dropdown-menu
              = render partial: '/layouts/navbar_categories_options'
          %li.dropdown
            %a{href: "/categories"}=t :shop
            - if user_signed_in?
              %li
                %a{type: "button", 'data-toggle': "dropdown", href: "/", 'aria-expanded': "false"}=t :my_account
                %ul.dropdown-menu
                  %li
                    =link_to t(:orders), orders_path, class: 'collapse-link'
                  %li
                    =link_to t(:settings), settings_path, class: 'collapse-link'
                  %li.divider{role: "separator"}
                  %li
                    =link_to t(:log_out), logout_path, class: 'collapse-link'
            - else
              %li
                =link_to t(:log_in), login_path
              %li
                =link_to t(:sign_up), signup_path

app/views/layouts/_navbar_categories_options.html.haml
%li
  =link_to t(:mobile_development), '/?category=mobile_development', class: 'collapse-link'
%li
  =link_to t(:photo), '/?category=photo', class: 'collapse-link'
%li
  =link_to t(:web_design), '/?category=web_design', class: 'collapse-link'
%li
  =link_to t(:web_development), '/?category=web_development', class: 'collapse-link'

app/views/layouts/active_admin_logged_out.html.haml
=render template: "layouts/application"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{charset: "UTF-8"}
    %meta{name: "viewport", content: "width=device-width"}
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title BookStore
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %link{href: "https://fonts.googleapis.com/css?family=Open+Sans:300,400,600", rel: "stylesheet"}
  %body
    = render :partial => '/layouts/header'
    %div.container
      %p.notice= notice
      %p.alert= alert
    = yield
    = render :partial => '/layouts/footer'
    %script{src: "https://use.fontawesome.com/67602d7308.js"}